<?php
/**
 * nessus-report-parser -- hosts.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:21
 */

include(__DIR__ . '/../includes/nessusReportHeader.phtml');

foreach ($reportData as $vulnerability) {
    echo '

<div class="headers"><br> ' . htmlspecialchars($vulnerability[0][0]['vulnerability']) . ' </div>
<table>

';

    $loop = 0;
    foreach ($vulnerability[1] as $hostObj) {

        if ($loop == 0) {
            $loop++;
            print('<tr>');
        }

        echo '
                    <td>' . htmlspecialchars($hostObj['host_id']) . '</td>
                    <td>' . htmlspecialchars(strtoupper($hostObj['protocol'])) . '/' . htmlspecialchars($hostObj['port']) . '</td>
                    ';
        $loop++;
        if ($loop == 5) {
            echo '</tr>';
            $loop = 0;
            continue;
        }

    }


    echo '</tr>';
    echo '</table>';

}

include(__DIR__ . '/../includes/footer.phtml');
