<?php
/**
 * nessus-report-parser -- header.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 16:18
 */

if (!array_key_exists('name', $_SESSION))
{
    $username = 'Not Logged In';
}
else
{
    $username = htmlspecialchars($_SESSION['name']);
}

echo '  <html>
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
                <link rel="stylesheet" type="text/css" href="/css/main.css">
                <title>RandomStorm Report Generator</title>
            </head>
            <body>
                <div class="menu" ><a href="/"><img src="/images/logo.png" alt="RandomStorm Limited" /></a>
                <nav>
                    <ul>
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li>
                            <a href="#">Reports <span class="caret"></span></a>
                            <div>
                                <ul>
                                    <li>
                                        <a href="/nessus">Nessus</a>
                                    </li>
                                    <li>
                                        <a href="/opendlp">OpenDLP</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#">File Management<span class="caret"></span></a>
                            <div>
                                <ul>
                                    <li>
                                        <a href="/nessusMenu">Nessus</a>
                                    </li>
                                    <li>
                                        <a href="/openDlpMenu">OpenDLP</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#">' . $username . '<span class="caret"></span></a>
                            <div>
                                <ul>
                                    <li>
                                        <a href="/admin/adduser">Add User</a>
                                    </li>
                                    <li>
                                        <a href="/admin/changepass">Change Password</a>
                                    </li>
                                    <li>
                                        <a href="/logout">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
';