<?php
/**
 * nessus-report-parser - hidden.phtml.
 * User: simonbeattie
 * Date: 18/06/2014
 * Time: 11:03
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

$severity = $app->request()->get('result');
$plugin = $app->request()->get('plugin');

echo '
<p class="header">Change Severity Levels</p>

<p>WORK - IN  - PROGRESS (i.e. this doesn\'t change anything!)</p>
';

if ($severity){
echo '<p class="green">Changed severity of plugin '.$plugin.' to '.$severity.'</p>';
}
echo '
<div class="vulnFormContainer">
    <ul class="vulnForm">
';

foreach ($vulnerabilities as $vulnerability) {

    if (($vulnerability['risk_factor'] == "High") || ($vulnerability['risk_factor'] == "Critical")) {
        $colour = "red";
    } elseif ($vulnerability['risk_factor'] == "Medium") {
        $colour = "orange";
    } elseif ($vulnerability['risk_factor'] == "Low") {
        $colour = "green";
    } elseif ($vulnerability['risk_factor'] == "None") {
        $colour = "blue";
    } else {
        $colour = "blue";
    }

    echo'
        <li>
            <form method="post">
            <label class="' . $colour . '">' . htmlspecialchars($vulnerability['vulnerability']) . '</label>
            <select name="severity">
            <option selected="selected">'. $vulnerability['severity'] .'</option>';

            for ($i = 0.0; $i <= 10.0; $i+=0.1)
            {
                echo '<option value ="' . $i . '">' . $i . '</option>';
            }

    echo '  </select>
                <input type="hidden" name="plugin" value="' . $vulnerability['pluginID'] . '">
                <input type="submit"></form>
            </li>
                ';
}
echo '</ul>
</div>';



include(__DIR__ . '/../includes/footer.phtml');