<?php
/**
 * nessus-report-parser - hidden.phtml.
 * User: simonbeattie
 * Date: 18/06/2014
 * Time: 11:03
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

$severity = $app->request()->get('result');
$plugin = $app->request()->get('plugin');

echo '
<p class="header">Change Vulnerability Risk</p>
';

echo '
<div class="vulnFormContainer">
    <ul class="vulnForm">
';

foreach ($vulnerabilities as $vulnerability) {

    if ($vulnerability['risk_factor'] == 'None')
    {
        $vulnerability['risk_factor'] = 'Informational';
    }

    if (($vulnerability['risk_factor'] == "High") || ($vulnerability['risk_factor'] == "Critical")) {
        $colour = "red";
    } elseif ($vulnerability['risk_factor'] == "Medium") {
        $colour = "orange";
    } elseif ($vulnerability['risk_factor'] == "Low") {
        $colour = "green";
    } elseif ($vulnerability['risk_factor'] == "None") {
        $colour = "blue";
    } else {
        $colour = "blue";
    }

    echo'<li>';

    if (array_key_exists('updated', $vulnerability))
    {
        echo '

            <form method="post">
            <label class="' . $colour . '">' . htmlspecialchars($vulnerability['vulnerability']) . '</label>

            <input type="hidden" name="remove" value="' . $vulnerability['pluginID'] . '">
            <input type="submit" value="Reset"></form>
        ';
    }
    else
    {
        echo'
            <form method="post">
            <label class="' . $colour . '">' . htmlspecialchars($vulnerability['vulnerability']) . '</label>
            <select name="severity">
                <option selected="selected">'. $vulnerability['risk_factor'] .'</option>
                <option value ="Critical">Critical</option>
                <option value ="High">High</option>
                <option value ="Medium">Medium</option>
                <option value ="Low">Low</option>
                <option value ="Informational">Informational</option>
            </select>
        <input type="hidden" name="plugin" value="' . $vulnerability['pluginID'] . '">
        <input type="submit" value="Update"></form>
        ';
    }
echo '
        </li>
                ';
}
echo '</ul>
</div>';



include(__DIR__ . '/../includes/footer.phtml');