<?php
/**
 * nessus-report-parser -- nessusIndex.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:25
 */


include(__DIR__ . '/../includes/menuHeader.phtml');

echo '
<p class="header">Imported Nessus Reports</p>

<div class="reportFormContainer">
    <ul class="reportForm">
';


    foreach ($reports as $report) {

        if ( $report['completed'] != $report['hosts'] )
        {
            $label = round(intval($report['completed']) / intval($report['hosts']) * 100)  . '% Imported';
        }
        else
        {
            $label = 'Select Report';
        }

        echo'
        <li>
            <label>' . htmlspecialchars($report['report_name']) . ' (' . htmlspecialchars($report['created']) . ')</label>
            <select onchange="location = this.options[this.selectedIndex].value; loadingScreen()">
                <option selected> '. $label .' </option>
                <option value="hosts/' . $report['id'] . '/' . $severity . '">Hosts Report</option>
                <option value="vulnerabilities/' . $report['id'] . '/' . $severity . '">Vulnerabilities Report</option>
                <option value="descriptions/' . $report['id'] . '/' . $severity . '">Descriptions Report</option>
                <option value="pci/' . $report['id'] . '">PCI Report</option>
            </select>
        </li>
            ';
    }
    echo '</ul>
</div>';

include(__DIR__ . '/../includes/footer.phtml');

