<?php
/**
 * nessus-report-parser -- nessusIndex.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:25
 */


include(__DIR__ . '/../includes/menuHeader.phtml');

echo '
<p><b>Imported Nessus Reports</b>

<div class="reportList">
';

    foreach ($reports as $report) {
        echo'
            <p>' . $report['report_name'] . ' (' . $report['created'] . ')
            <label>
                <select onchange="location = this.options[this.selectedIndex].value; loadingScreen()">
                    <option selected> Select Report </option>
                    <option value="hosts/' . $report['id'] . '/' . $severity . '">Hosts Report</option>
                    <option value="vulnerabilities/' . $report['id'] . '/' . $severity . '">Vulnerabilities Report</option>
                    <option value="descriptions/' . $report['id'] . '/' . $severity . '">Descriptions Report</option>
                    <option value="pci/' . $report['id'] . '">PCI Report</option>
                </select>
            </label>

            ';
    }
    echo '</div>';

include(__DIR__ . '/../includes/footer.phtml');
