<?php
/**
 * nessus-report-parser - shown.phtml.
 * User: simonbeattie
 * Date: 18/06/2014
 * Time: 12:13
 */

include(__DIR__ . '/../includes/menuHeader.phtml');


echo '
<p class="header">Vulnerabilities Shown On Reports</p>
<p>Please select any vulnerabilities that you do not wish to show up on your reports. You can re-add these from the hidden screen.</p>
<div class="vulnFormContainer">
    <ul class="vulnForm">
';

foreach ($vulnerabilities as $vulnerability) {

    if (($vulnerability['risk_factor'] == "High") || ($vulnerability['risk_factor'] == "Critical")) {
        $colour = "red";
    } elseif ($vulnerability['risk_factor'] == "Medium") {
        $colour = "orange";
    } elseif ($vulnerability['risk_factor'] == "Low") {
        $colour = "green";
    } elseif ($vulnerability['risk_factor'] == "None") {
        $colour = "blue";
    } else {
        $colour = "blue";
    }

    echo'
        <li>
            <label class="' . $colour . '">' . htmlspecialchars($vulnerability['vulnerability']) . '</label>
            <select onchange="location = this.options[this.selectedIndex].value">
                <option selected> Select </option>
                <option value="/ignored/add/' . $vulnerability['pluginID'] . '">Hide</option>
            </select>
        </li>
            ';
}
echo '</ul>
</div>';



include(__DIR__ . '/../includes/footer.phtml');