<?php
/**
 * nessus-report-parser -- nessusIndex.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:25
 */

echo '  <html>
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
                <link rel="stylesheet" type="text/css" href="/css/main.css">
                <title>RandomStorm Report Generator</title>
                <script language="javascript">

';
echo "
                    function loadingScreen(){
                        document.body.innerHTML += '<div class=\"loading\">Loading&#8230;</div>';
                    }
                </script>
            </head>
";

echo '<div class="menu">';
echo '<div><a href="/" onclick="loadingScreen()"><img src="/images/logo.png" alt="RandomStorm Limited" /></a></div>';
echo '<div>
<br>
<b>Options</b>
<br>
<p><a class="myButton"; href="/opendlp" onclick="loadingScreen()">OpenDLP Reports</a>
<p><a class="myButton"; href="/files" onclick="loadingScreen()">File Management</a>
<p><a class="myButton"; href="/logout" onclick="loadingScreen()">Logout</a>
<p><b>Imported Nessus Reports</b>
';


    foreach ($reports as $report) {
        echo '<p><b>' . $report['report_name'] . '</b> (' . $report['created'] . ') - ';
        echo '
            <label>
                <select onchange="location = this.options[this.selectedIndex].value; loadingScreen()">
                    <option selected> Select Report </option>
                    <option value="hosts/' . $report['id'] . '/' . $severity . '">Hosts Report</option>
                    <option value="vulnerabilities/' . $report['id'] . '/' . $severity . '">Vulnerabilities Report</option>
                    <option value="descriptions/' . $report['id'] . '/' . $severity . '">Descriptions Report</option>
                    <option value="pci/' . $report['id'] . '">PCI Report</option>
                </select>
            </label>

            ';
    }
    echo '</div>';
