<?php
/**
 * nessus-report-parser -- openDlpIndex.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:26
 */

echo '  <html>
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
                <link rel="stylesheet" type="text/css" href="/css/main.css">
                <title>RandomStorm Report Generator</title>
                <script language="javascript">

';
echo "
                    function loadingScreen(){
                        document.body.innerHTML += '<div class=\"loading\">Loading&#8230;</div>';
                    }
                </script>
            </head>
";

echo '<div class="menu">';
echo '<div><a href="/opendlp" onclick="loadingScreen()"><img src="/images/logo.png" alt="RandomStorm Limited" /></a></div>';
echo '<div>
<br>
<b>Options</b>
<br>
<p><a class="myButton"; href="/" onclick="loadingScreen()">Nessus Reports</a>
<p><a class="myButton"; href="/files" onclick="loadingScreen()">File Management</a>
<p><b>Imported OpenDLP Reports</b>
';



if (!$this->getOpenDlpList())
{
    echo "There are no reports available on the system<br>";
} else {

    foreach ($this->getOpenDlpList() as $name => $hash) {
        echo '<p><b>' . $name . '</b> ';
        echo '
<label>
    <select onchange="location = this.options[this.selectedIndex].value; loadingScreen()">
        <option selected> Select Report </option>
        <option value="/opendlp/' . $name . '">OpenDLP Overview Report</option>
    </select>
</label>

            ';
    }
    echo '</div>';
}