<?php
/**
 * nessus-report-parser -- pci.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:22
 */

echo '

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="/css/main.css">
<title>PCI View</title>
<script language=\"javascript\">


function loadingScreen(){
   document.body.innerHTML += \'<div class="loading">Loading&#8230;</div>\';
}
</script>
</head>

<a onclick="loadingScreen()" class="myButton" href="/nessus">Return to Menu</a></p>
<table border=0 cellpadding=0 cellspacing=0>

';


$ignoredInfos = array(
    "Service Detection",
    "Nessus SYN scanner",
    "Web-Server Allows Password Auto-Completion",
    "IPSEC Internet Key Exchange (IKE) Version 1 Detection",
);

$tidyNames = array(
    "ssh"        => "Secure Shell Protocol",
    "dns"        => "Domain Name Service",
    "ftp"        => "File Transfer Protocol",
    "mysql"      => "MySQL Database",
    "smtp"       => "Simple Mail Transfer Protocol",
    "http"       => "Hypertext Transfer Protocol",
    "subversion" => "Subversion Version Manager",
    "pptp"       => "Point-to-Point Tunneling Protocol",
    "www"        => "World Wide Web",
    "savant"     => "Savant",
    "pop3"       => "Post Office Protocol v3",
    "imap"       => "Internet Message Access Protocol"
);

$risks = array(
    "Critical" => "CRITICAL",
    "High"     => "HIGH",
    "Medium"   => "MEDIUM",
    "Low"      => "LOW",
    "None"     => "INFO"
);

$data = array();
foreach ($reportData as $hostData) {
    foreach ($hostData['vulnerabilities'] as $vulnerability) {

        if (array_key_exists($vulnerability['risk'], $risks)) {
            $risk = $risks[$vulnerability['risk']];
        } else {
            $risk = $vulnerability['risk'];
        }

        $data[] = array(
            'ip'       => ip2long($hostData['hostname']),
            'vuln'     => $vulnerability['name'],
            'risk'     => $risk,
            'severity' => $vulnerability['severity'],
            'port'     => strtoupper($vulnerability['protocol']) . "/" . $vulnerability['port'],
            'service'  => $vulnerability['service']
        );
    }

}


usort($data, function ($firstArrayElement, $secondArrayElement) {
    $first = $firstArrayElement['ip'];
    $second = $secondArrayElement['ip'];

    $ret = strcmp($first, $second);
    if ($ret == 0) {
        $firstSeverity = (float)$firstArrayElement['severity'];
        $secondSeverity = (float)$secondArrayElement['severity'];

        if ($secondSeverity > $firstSeverity) {
            return 1;
        } elseif ($firstSeverity > $secondSeverity) {
            return -1;
        } elseif ($firstSeverity == $secondSeverity) {
            return 0;
        }
    }

    return $ret;
});

$ip = "";


$counts = array();
foreach ($data as $value) {
    foreach ($value as $key2 => $value2) {
        if ($key2 == "ip") {
            $index = $value2;
            if (array_key_exists($index, $counts)) {
                $counts[$index]++;
            } else {
                $counts[$index] = 1;
            }
        }
    }
}

foreach ($data as $vuln) {
    if ((!in_array($vuln['vuln'], $ignoredInfos)) && ($vuln['risk'] == "INFO")) {
        $counts[$vuln['ip']]--;
    }
}
$started = 0;
foreach ($data as $vuln) {

    $notes = "<td class=\"black\">N/A</td>";

    $options = array(
        "HIGH"     => "red",
        "CRITICAL" => "red",
        "MEDIUM"   => "orange",
        "LOW"      => "green",
        "INFO"     => "blue",
    );

    if ($vuln['severity'] > 4) {
        $status = 'FAIL';
        $statusColour = 'fail';
    } else {
        $status = 'PASS';
        $statusColour = 'pass';
    }

    if ($vuln['severity'] == 0) {
        $vuln['severity'] = 'N/A';
        $sevColour = "black";
    } else {
        $sevColour = $options[$vuln['risk']];
    }

    if ((!in_array($vuln['vuln'], $ignoredInfos)) && ($vuln['risk'] == "INFO")) {
        continue;
    }

    if (array_key_exists($vuln['service'], $tidyNames)) {
        $service = $tidyNames[$vuln['service']];
    } else {
        $service = $vuln['service'];
    }

    if ($vuln['vuln'] == "Nessus SYN scanner") {
        $vuln['vuln'] = "Special Note";
    }

    if (($vuln['vuln'] == "Service Detection") || ($vuln['vuln'] == "Special Note")) {
        $vuln['vuln'] = $vuln['vuln'] . ": " . $service;
    }

    if (($vuln['vuln'] == "Service Detection: File Transfer Protocol") || ($vuln['vuln'] == "Service Detection: Telnet Protocol")) {
        $notes = "<td class=\"orange\">CLEAR TEXT</td>";
        $status = "FAIL";
        $statusColour = "red";
    }

    if ($ip == long2ip($vuln['ip'])) {

        print("
            <tr>
                  <td>" . $vuln['vuln'] . "</td>
                  <td>" . $vuln['port'] . "</td>
                  <td class=" . $options[$vuln['risk']] . ">" . $vuln['risk'] . "</td>
                  <td class=" . $sevColour . ">" . $vuln['severity'] . "</td>
                  <td class=" . $statusColour . ">" . $status . "</td>
                  " . $notes . "
             </tr>
            ");
    } else {
        if ($started == 0) {
            $started++;
        } else {
            print('
                <tr>
                  <td class="black">Host Summary:</td>
                  <td class="black" colspan=6>Unable to resolve.</td>
                </tr>
            ');
        }

        print("
            <tr>
                  <td border:solid 1pt gray; vertical-align: top; rowspan=\"" . $counts[$vuln['ip']] . "\">" . long2ip($vuln['ip']) . "</td>
                  <td>" . $vuln['vuln'] . "</td>
                  <td>" . $vuln['port'] . "</td>
                  <td class=" . $options[$vuln['risk']] . ">" . $vuln['risk'] . "</td>
                  <td class=" . $sevColour . ">" . $vuln['severity'] . "</td>
                  <td class=" . $statusColour . ">" . $status . "</td>
                  " . $notes . "
             </tr>

            ");

        $ip = long2ip($vuln['ip']);
    }

}

echo "</table>";