<?php
/**
 * nessus-report-parser -- vulnerabilites.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:23
 */

echo '

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="/css/main.css">
<title>Vulnerability View</title>
<script language=\"javascript\">

function loadingScreen(){
   document.body.innerHTML += \'<div class="loading">Loading&#8230;</div>\';
}
</script>
</head>

<a onclick="loadingScreen()" class="myButton" href="/nessus">Return to Menu</a></p>
<table border=0 cellpadding=0 cellspacing=0>

';


$data = array();
$rowCount = 0;
foreach ($reportData as $hostData) {
    $potentialOperatingSystems = explode(PHP_EOL, $hostData['OS']);
    $OS = trim(array_shift($potentialOperatingSystems));

    if ($hostData->fqdn == "") {
        $name = $hostData['netbios'];
    } else {
        $name = $hostData['fqdn'];
    }

    if (!$name) {
        $name = "Unable to accurately identify";
    }

    foreach ($hostData['vulnerabilities'] as $vulnerability) {
        $data[] = array(
            'ip'       => ip2long($hostData['hostname']),
            'name'     => $name,
            'os'       => $OS,
            'vuln'     => $vulnerability['name'],
            'risk'     => $vulnerability['risk'],
            'severity' => $vulnerability['severity']);
    }

}

usort($data, function ($firstArrayElement, $secondArrayElement) {
    $first = $firstArrayElement['ip'];
    $second = $secondArrayElement['ip'];

    $ret = strcmp($first, $second);
    if ($ret == 0) {
        $firstSeverity = (float)$firstArrayElement['severity'];
        $secondSeverity = (float)$secondArrayElement['severity'];

        if ($secondSeverity > $firstSeverity) {
            return 1;
        } elseif ($firstSeverity > $secondSeverity) {
            return -1;
        } elseif ($firstSeverity == $secondSeverity) {
            return 0;
        }
    }

    return $ret;
});

$ip = "";


$counts = array();
foreach ($data as $value) {
    foreach ($value as $key2 => $value2) {
        if ($key2 == "ip") {
            $index = $value2;
            if (array_key_exists($index, $counts)) {
                $counts[$index]++;
            } else {
                $counts[$index] = 1;
            }
        }
    }
}


foreach ($data as $vuln) {
    if (($vuln['risk'] == "High") || ($vuln['risk'] == "Critical")) {
        $colour = "red";
    } elseif ($vuln['risk'] == "Medium") {
        $colour = "orange";
    } elseif ($vuln['risk'] == "Low") {
        $colour = "green";
    } elseif ($vuln['risk'] == "Info") {
        $colour = "blue";
    } else {
        $colour = "blue";
    }


    if ($ip == long2ip($vuln['ip'])) {
        $rowCount++;
        print("
            <tr>
                <td class=" . $colour . ">" . $vuln['vuln'] . "</td>
                <td class=" . $colour . ">" . $vuln['risk'] . "</td>
                <td class=" . $colour . ">" . $vuln['severity'] . "</td>
            </tr>
            ");
    } else {
        $rowCount++;
        if ($rowCount > 900)
        {
            echo "</table>";
            echo "<p><hr>";
            echo "<p><table border=0 cellpadding=0 cellspacing=0>";
            $rowCount = 0;
        }
        print("
            <tr>
                <td border:solid 1pt gray; vertical-align: top; rowspan='" . $counts[$vuln['ip']] . "'>" . long2ip($vuln['ip']) . "</td>
                <td border:solid 1pt gray; vertical-align: top; rowspan='" . $counts[$vuln['ip']] . "'>" . $vuln['name'] . "</td>
                <td border:solid 1pt gray; vertical-align: top; rowspan='" . $counts[$vuln['ip']] . "'>" . $vuln['os'] . "</td>
                <td class=" . $colour . ">" . $vuln['vuln'] . "</td>
                <td class=" . $colour . ">" . $vuln['risk'] . "</td>
                <td class=" . $colour . ">" . $vuln['severity'] . "</td>
            </tr>

            ");

        $ip = long2ip($vuln['ip']);


    }

}
