<?php
/**
 * nessus-report-parser -- changePass.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 17:39
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

echo '

<p class="header">Change Your Password</p>
<div class="userForm">
    <form method="post">
        <ul class="form">
            <li>
            	<label for="oldPassword">Existing Password</label>
            	<input type="password" name="oldpass" placeholder="Existing Password" id="oldPassword">
        	</li>
            <li>
            	<label for="newPass">New Password</label>
            	<input type="password" name="newpass" placeholder="New Password" id="newPass">
        	</li>
            <li>
            	<label for="repeatPass">Repeat Password</label>
            	<input type="password" name="repeat" placeholder="Repeat Password" id="repeatPass">
        	</li>
            <li><input type="submit" value="Change"></form></li>
        </ul>
    </form>
</div>



';

$success = $app->request()->get('result');
switch ($success)
{
    case 'success':
        echo '<p><a href="/" class="green">Password changed successfully - Click to return to the menu</a></p>';
        break;
    case 'match':
        echo '<p><a class="red">Your passwords did not match, please try again</a></p>';
        break;
    case 'failed':
        echo '<p><a class="red">The password change failed, please try again</a></p>';
        break;
    case 'wrongPass':
        echo '<p><a class="red">You have entered the wrong password, please try again</a></p>';
        break;
}
echo '</div>';

include(__DIR__ . '/../includes/footer.phtml');
