<?php
/**
 * nessus-report-parser -- login.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 18:06
 */

$badLogin = $app->request()->get('loggedIn');

include(__DIR__ . '/../includes/menuHeader.phtml');

echo '

            <p class="header">Please enter your login credentials</p>
            <div class="userForm">
                <form method="post">
                    <ul class="form">
                        <li>
                            <label for="username">Username</label>
                            <input type="text" name="username" placeholder="Email Address" id="username">
                        </li>
                        <li>
                            <label for="password">Password</label>
                            <input type="password" name="password" placeholder="Password" id="password">
                        </li>
                        <li>
                            <input type="submit" value="Login">
                        </li>
                    </ul>
                </form>
            </div>
 ';
if($badLogin)
{
    echo '<strong class="red">You have entered an incorrect username and password!</strong>';
}
echo '         </div>';

include(__DIR__ . '/../includes/footer.phtml');