<?php
/**
 * nessus-report-parser -- changePass.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 17:39
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

$severity = $userDetails[0]['severity'];

echo '
<p class="header">Change Your Severity</p>
            <p>Your current severity level is: ' . $severity . '</p>';

echo '
<div class=userForm>
<form method="post">
    <p id="range">' . $severity . '</p>';
echo '
    <input class="slider-width100" type="range" min="0.0" max="10.0" onchange="showValue(this.value)" value="' . $severity . '" name="severity" step="0.1" placeholder="Severity"><br>

    <script type="text/javascript">
        function showValue(newValue)
        {
            document.getElementById("range").innerHTML=newValue;
        }
    </script>

    <input type="submit" value="Change"></form>
<div>
';

$success = $app->request()->get('result');
if (isset($success))
{
    switch ($success)
    {
        case 'success':
            echo '<p><a class="green">Severity changed successfully</a></p>';
            break;
        case 'failed':
            echo '<p><a class="red">The Severity change failed, please try again</a></p>';
            break;
    }
}
echo '</div>';

include(__DIR__ . '/../includes/footer.phtml');
