<?php
/**
 * nessus-report-parser -- nessusFiles.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 16:57
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

if ($app->request()->get('upload'))
{
    if ($app->request()->get('upload') == 'success' )
    {
        $result = '<a class="green">The file has been successfully uploaded</a>';
    }
    else
    {
        $result = '<a class="red">The file has failed to upload</a>';
    }
}
if ($app->request()->get('admin'))
{
    if ($app->request()->get('admin') == 'success' )
    {
        $admin = '<a class="green">Successful</a>';
    }
    elseif ($app->request()->get('admin') == 'none')
    {
        $admin = '<a class="red">Failed, you must select a report</a>';
    }
    elseif ($app->request()->get('admin') == 'multiple')
    {
        $admin = '<a class="red">Failed, you can only import a single report</a>';
    }
    else
    {
        $admin = '<a class="red">Failed, please try again</a>';
    }
}

echo '

<form action="/nessusMenu/admin" method="post">
    <p><b>Stored Nessus Reports</b></p>

<table class="center">
        <tr>
            <td>Report Name</td>
            <td>Select</td>
        </td>

';
        foreach ($reports as $file => $hash) {
            echo '  <tr>
                        <td> ' . htmlspecialchars($file) . ' </td>
                        <td><input type="checkbox" name="reports[]" value="' . $hash . '" /></td>
                    </tr>';
        }

        echo '      </table>';
            if(isset($admin)){echo $admin.'<br>';};
        echo '
                    <input type="submit" name="formSubmit" value="Delete Nessus"/>
                    <input type="submit" name="formSubmit" value="Merge"/>
                    <input type="submit" name="formSubmit" value="Import"/>
                </form>


<p><b>Upload Nessus File</b></p>
';

if(isset($result)){echo $result;};

echo '
<form action="/nessusMenu/upload" method="post" enctype="multipart/form-data">
  <input type="file" name="uploadFile" size="50" maxlength="25" />
  <input type="submit" name="upload" value="Upload Nessus XML"" />
</form>
</div>
';



include(__DIR__ . '/../includes/footer.phtml');
