<?php
/**
 * nessus-report-parser -- openDlpFiles.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 16:57
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

if ($app->request()->get('upload'))
{
    if ($app->request()->get('upload') == 'success' )
    {
        $result = '<p></p><a class="green">The file has been successfully uploaded</a></p>';
    }
    elseif ($app->request()->get('upload') == 'notvalid')
    {
        $result = '<p><a class="red">That file has not been identified as a valid OpenDLP file</a></p>';
    }
    else
    {
        $result = '<p><a class="red">The file has failed to upload</a></p>';
    }
}
if ($app->request()->get('admin'))
{
    if ($app->request()->get('admin') == 'success' )
    {
        $admin = '<p><a class="green">Successful</a></p>';
    }
    elseif ($app->request()->get('admin') == 'none')
    {
        $admin = '<p><a class="red">Failed, you must select a report</a></p>';
    }
    elseif ($app->request()->get('admin') == 'multiple')
    {
        $admin = '<p><a class="red">Failed, you can only import a single report</a></p>';
    }
    else
    {
        $admin = '<p><a class="red">Failed, please try again</a></p>';
    }
}

echo '
<p class="header">Stored OpenDLP Reports</p>
<div class="fileMenu">
    <form action="/openDlpMenu/admin" method="post">
        <p>
        <table>
            <tr>
                <td>Report Name</td>
                <td>Select</td>
            </td>
';
foreach ($reports as $file => $hash) {
echo '
        <tr>
            <td> ' . htmlspecialchars($file) . ' </td>
            <td><input type="checkbox" name="reports[]" value="' . $hash . '" /></td>
        </tr>
';
}
echo '
        </table>
        </p>
';
if(isset($admin))
{
    echo $admin;
};
echo '
        <input type="submit" name="formSubmit" value="Delete OpenDLP"/>
    </form>
';

echo '
<p class="header">Upload OpenDLP File</p>
';
if(isset($result)){echo $result;};
echo'
    <form action="/openDlpMenu/upload" method="post" enctype="multipart/form-data">
        <input type="file" name="uploadFile" size="50" maxlength="25" />
        <input type="submit" name="upload" value="Upload OpenDLP XML" />
    </form>
</div>
';

include(__DIR__ . '/../includes/footer.phtml');
